export const questions = [
  "What is 2 + 2?",
  "What is the meaning of mathematics?",
  "What is bla bla bla bla?",
];

export const getColor = (color: number) => {
  if (color == -5) {
    return "#8f8fb1";
  } else if (color <= 10) {
    return "#ff0000";
  } else if (color > 10 && color <= 20) {
    return "#e91600";
  } else if (color > 20 && color <= 30) {
    return "#d22d00";
  } else if (color > 30 && color <= 40) {
    return "#ff8105";
  } else if (color > 40 && color <= 50) {
    return "#ffaf05";
  } else if (color > 50 && color <= 60) {
    return "#ffd605";
  } else if (color > 60 && color <= 70) {
    return "#2bd500";
  } else if (color > 70 && color <= 80) {
    return "#2bd500";
  } else if (color > 80 && color <= 90) {
    return "#1ee100";
  } else if (color > 90 && color <= 100) {
    return "#00ff00";
  }
};

export const qs = [
  {
    _id: "6702bd99c57feb7bce022f41",
    objCode: "NM_6",
    question: "What is a prime number?",
    optionA: "A number that has only two divisors: 1 and itself.",
    optionB:
      "A number that can be divided evenly by any number less than or equal to it.",
    optionC: "A number that is always even.",
    optionD: "A number that is always odd.",
    answer: "A",
    difficultyLevel: "1",
    subject: "Mathematics",
    bloomLevel: "Remembering",
    explanation:
      "A prime number is a number that has only two divisors: 1 and itself.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:40:57.130Z",
    updatedAt: "2024-10-06T16:40:57.130Z",
    __v: 0,
  },
  {
    _id: "6702bd99c57feb7bce022f44",
    objCode: "NM_6",
    question: "Which of the following is a prime number?",
    optionA: "17",
    optionB: "18",
    optionC: "20",
    optionD: "22",
    answer: "A",
    difficultyLevel: "1",
    subject: "Mathematics",
    bloomLevel: "Remembering",
    explanation:
      "17 is a prime number because it has only two divisors: 1 and itself.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:40:57.649Z",
    updatedAt: "2024-10-06T16:40:57.649Z",
    __v: 0,
  },
  {
    _id: "6702bd9ac57feb7bce022f47",
    objCode: "NM_6",
    question: 'Define the term "composite number."',
    optionA: "A number that has more than two divisors.",
    optionB: "A number that is not a prime number.",
    optionC: "A number that is always even.",
    optionD: "A number that is always odd.",
    answer: "B",
    difficultyLevel: "1",
    subject: "Mathematics",
    bloomLevel: "Remembering",
    explanation:
      "A composite number is a number that is not a prime number. It has more than two divisors.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:40:58.153Z",
    updatedAt: "2024-10-06T16:40:58.153Z",
    __v: 0,
  },
  {
    _id: "6702bd9ac57feb7bce022f4a",
    objCode: "NM_6",
    question: "Identify the largest prime number less than 25.",
    optionA: "11",
    optionB: "13",
    optionC: "15",
    optionD: "17",
    answer: "B",
    difficultyLevel: "1",
    subject: "Mathematics",
    bloomLevel: "Remembering",
    explanation:
      "The largest prime number less than 25 is 13. The other numbers given are also prime numbers, but they are larger than 25.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:40:58.689Z",
    updatedAt: "2024-10-06T16:40:58.689Z",
    __v: 0,
  },
  {
    _id: "6702bd9bc57feb7bce022f4d",
    objCode: "NM_6",
    question: "What is a prime number and how can you identify it?",
    optionA:
      "A prime number is a number that has only two factors, 1 and itself. It can be identified by dividing the number by all other numbers up to its square root.",
    optionB:
      "A prime number is a number that has an even number of factors. It can be identified by dividing the number by its square root and checking if any other number divides it evenly.",
    optionC:
      "A prime number is a number that has more than two factors. It can be identified by dividing the number by its square root and checking if any other number divides it without leaving a remainder.",
    optionD:
      "A prime number is a number that has fewer than two factors. It can be identified by dividing the number by its square root and checking if any other number divides it with a remainder.",
    answer: "A",
    difficultyLevel: "1",
    subject: "Mathematics",
    bloomLevel: "Understanding",
    explanation:
      "A prime number is a positive integer greater than 1 that has no positive divisors other than 1 and itself. The common method to check if a number is prime is by dividing it by all numbers up to its square root.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:40:59.049Z",
    updatedAt: "2024-10-06T16:40:59.049Z",
    __v: 0,
  },
  {
    _id: "6702bd9bc57feb7bce022f50",
    objCode: "NM_6",
    question: "Explain why 1 is not considered a prime number.",
    optionA:
      "1 is considered a prime number because it has only two factors, 1 and itself.",
    optionB:
      "1 is not considered a prime number because it has more than two factors.",
    optionC:
      "1 is not considered a prime number because it has fewer than two factors.",
    optionD:
      "1 is considered a prime number because it cannot be divided evenly by any other number.",
    answer: "C",
    difficultyLevel: "1",
    subject: "Mathematics",
    bloomLevel: "Understanding",
    explanation:
      "1 is not considered a prime number because it has fewer than two factors. Although 1 can be considered a unit, it is not considered a prime number in the traditional sense of the term.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:40:59.531Z",
    updatedAt: "2024-10-06T16:40:59.531Z",
    __v: 0,
  },
  {
    _id: "6702bd9bc57feb7bce022f53",
    objCode: "NM_6",
    question:
      'Interpret the following statement: "The prime number 17 has 16 divisors."',
    optionA:
      "The statement is incorrect because 17 has only two divisors, 1 and 17.",
    optionB: "The statement is incorrect because 17 has more than 16 divisors.",
    optionC:
      "The statement is correct because 17 has 16 divisors when considering negative divisors as well.",
    optionD:
      "The statement is correct because 17 has 16 divisors when considering fractions as divisors.",
    answer: "A",
    difficultyLevel: "1",
    subject: "Mathematics",
    bloomLevel: "Understanding",
    explanation:
      "The statement is incorrect because 17 has only two divisors, 1 and 17. Prime numbers have only two distinct positive divisors: 1 and the number itself.",
    validationResult:
      'Question 4: [Incorrect] The correct statement should be: "The prime number 17 has only two distinct positive divisors, 1 and 17." or "A prime number like 17 has only two distinct positive divisors, 1 and itself."',
    isCorrect: false,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:40:59.896Z",
    updatedAt: "2024-10-06T16:40:59.896Z",
    __v: 0,
  },
  {
    _id: "6702bd9cc57feb7bce022f56",
    objCode: "NM_6",
    question: "Summarize the properties of prime numbers.",
    optionA:
      "Prime numbers are positive integers greater than 1 that have an even number of factors.",
    optionB:
      "Prime numbers are positive integers greater than 1 that have more than two factors.",
    optionC:
      "Prime numbers are positive integers greater than 1 that have only two factors, 1 and themselves.",
    optionD:
      "Prime numbers are positive integers greater than 1 that have fewer than two factors.",
    answer: "C",
    difficultyLevel: "1",
    subject: "Mathematics",
    bloomLevel: "Understanding",
    explanation:
      "Prime numbers are positive integers greater than 1 that have only two factors, 1 and themselves. They are the building blocks of all integers and are essential in many mathematical concepts, such as factoring, the Fundamental Theorem of Arithmetic, and the RSA encryption algorithm.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:41:00.268Z",
    updatedAt: "2024-10-06T16:41:00.268Z",
    __v: 0,
  },
  {
    _id: "6702bd9cc57feb7bce022f59",
    objCode: "NM_6",
    question:
      "If a number greater than 1 has no divisors other than 1 and itself, what type of number is it?",
    optionA: "Composite number",
    optionB: "Prime number",
    optionC: "Rational number",
    optionD: "Irrational number",
    answer: "B",
    difficultyLevel: "2",
    subject: "Mathematics",
    bloomLevel: "Applying",
    explanation:
      "A prime number is a positive integer greater than 1 that has no divisors other than 1 and itself.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:41:00.635Z",
    updatedAt: "2024-10-06T16:41:00.635Z",
    __v: 0,
  },
  {
    _id: "6702bd9dc57feb7bce022f5c",
    objCode: "NM_6",
    question:
      "Demonstrate how to determine if a number is prime by using the division method.",
    optionA:
      "Divide the number by 2 and check if there is any remainder. If there is, the number is not prime. If there isn't, divide the number by all the odd numbers up to its square root. If there is no divisor, the number is prime.",
    optionB:
      "Divide the number by all the prime numbers up to its square root. If there is no divisor, the number is prime.",
    optionC:
      "Divide the number by 2 and check if there is any remainder. If there is, the number is not prime. If there isn't, divide the number by all the prime numbers up to its square root. If there is no divisor, the number is prime.",
    optionD:
      "Divide the number by 2 and check if there is any remainder. If there is, the number is not prime. If there isn't, divide the number by all the composite numbers up to its square root. If there is no divisor, the number is prime.",
    answer: "A",
    difficultyLevel: "2",
    subject: "Mathematics",
    bloomLevel: "Applying",
    explanation:
      "The division method for checking if a number is prime involves dividing the number by 2 and checking for a remainder. If there is a remainder, the number is not prime. If there isn't, proceed to divide the number by all the odd numbers up to its square root. If there is no divisor, the number is prime.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:41:01.130Z",
    updatedAt: "2024-10-06T16:41:01.130Z",
    __v: 0,
  },
  {
    _id: "6702bd9dc57feb7bce022f5f",
    objCode: "NM_6",
    question: "How many prime numbers are there between 25 and 50?",
    optionA: "2",
    optionB: "3",
    optionC: "5",
    optionD: "7",
    answer: "C",
    difficultyLevel: "2",
    subject: "Mathematics",
    bloomLevel: "Applying",
    explanation:
      "The prime numbers between 25 and 50 are 29, 31, and 37. Therefore, there are 5 prime numbers in total, but only 3 of them are between 25 and 50.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:41:01.857Z",
    updatedAt: "2024-10-06T16:41:01.857Z",
    __v: 0,
  },
  {
    _id: "6702bd9ec57feb7bce022f62",
    objCode: "NM_6",
    question:
      "Illustrate how to find the largest prime factor of a composite number using the prime factorization method.",
    optionA:
      "Write down all the prime numbers up to the square root of the composite number. Divide the composite number by each prime number and find the number of times each prime number divides the composite number. Write down the prime number and its exponent. Repeat this process until you reach 1. The largest prime factor is the prime number with the highest exponent.",
    optionB:
      "Write down all the prime numbers up to the composite number. Divide the composite number by each prime number and find the first prime number that divides the composite number without leaving a remainder. Write down the prime number and its exponent as 1. Repeat this process until you reach 1. The largest prime factor is the prime number with the highest exponent.",
    optionC:
      "Write down all the prime numbers up to the composite number. Divide the composite number by each prime number and find the first prime number that divides the composite number without leaving a remainder. Write down the prime number and its exponent as 1. Repeat this process, but start with the last divisor and work your way back to the first divisor. The largest prime factor is the prime number with the highest exponent.",
    optionD:
      "Write down all the prime numbers up to the composite number. Divide the composite number by each prime number and find the first prime number that divides the composite number without leaving a remainder. Write down the prime number and its exponent as 1. Repeat this process, but start with the smallest divisor and work your way up to the largest divisor. The largest prime factor is the prime number with the highest exponent.",
    answer: "A",
    difficultyLevel: "2",
    subject: "Mathematics",
    bloomLevel: "Applying",
    explanation:
      "The prime factorization method involves writing down all the prime numbers up to the square root of the composite number. Divide the composite number by each prime number and find the number of times each prime number divides the composite number. Write down the prime number and its exponent. Repeat this process until you reach 1. The largest prime factor is the prime number with the highest exponent. This method is used to find the largest prime factor of a composite number.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:41:02.226Z",
    updatedAt: "2024-10-06T16:41:02.226Z",
    __v: 0,
  },
  {
    _id: "6702bd9ec57feb7bce022f65",
    objCode: "NM_6",
    question:
      "Analyze the properties of prime numbers in the first 100 natural numbers. Which of the following numbers is not a prime number in this range?",
    optionA: "2",
    optionB: "7",
    optionC: "12",
    optionD: "19",
    answer: "C",
    difficultyLevel: "2",
    subject: "Mathematics",
    bloomLevel: "Analyzing",
    explanation:
      "Prime numbers are only divisible by 1 and themselves. In the first 100 natural numbers, 12 is not a prime number because it has factors other than 1 and itself, specifically 2, 2, 3, 4, 6, and 12.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:41:02.650Z",
    updatedAt: "2024-10-06T16:41:02.650Z",
    __v: 0,
  },
  {
    _id: "6702bd9fc57feb7bce022f68",
    objCode: "NM_6",
    question:
      "Compare and distinguish between prime and composite numbers. Which of the following numbers is a composite number?",
    optionA: "1",
    optionB: "4",
    optionC: "17",
    optionD: "25",
    answer: "D",
    difficultyLevel: "2",
    subject: "Mathematics",
    bloomLevel: "Analyzing",
    explanation:
      "Prime numbers have only two distinct positive divisors: 1 and themselves. Composite numbers have more than two distinct positive divisors. In this case, 25 is a composite number because it has factors other than 1 and itself, specifically 1, 5, 5, 25.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:41:03.049Z",
    updatedAt: "2024-10-06T16:41:03.049Z",
    __v: 0,
  },
  {
    _id: "6702bd9fc57feb7bce022f6b",
    objCode: "NM_6",
    question:
      "Analyze the distribution of prime numbers in the first 100 natural numbers. Which statement about prime numbers in this range is true?",
    optionA: "The first 100 natural numbers have 50 prime numbers.",
    optionB: "The first 100 natural numbers have more than 50 prime numbers.",
    optionC: "The first 100 natural numbers have fewer than 25 prime numbers.",
    optionD: "The first 100 natural numbers have exactly 25 prime numbers.",
    answer: "B",
    difficultyLevel: "2",
    subject: "Mathematics",
    bloomLevel: "Analyzing",
    explanation:
      "According to the Prime Number Theorem, the density of primes increases without bound. Therefore, the first 100 natural numbers have more than 50 prime numbers.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:41:03.451Z",
    updatedAt: "2024-10-06T16:41:03.451Z",
    __v: 0,
  },
  {
    _id: "6702bd9fc57feb7bce022f6e",
    objCode: "NM_6",
    question:
      "Distinguish between a prime number and a prime factor. Which of the following numbers is a prime factor of 24?",
    optionA: "2",
    optionB: "3",
    optionC: "5",
    optionD: "12",
    answer: "A",
    difficultyLevel: "2",
    subject: "Mathematics",
    bloomLevel: "Analyzing",
    explanation:
      "A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself. A prime factor is a prime number that divides a given number. In the case of 24, the prime factors are 2, 2, 2, 3. Therefore, 2 is a prime factor of 24.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:41:03.857Z",
    updatedAt: "2024-10-06T16:41:03.857Z",
    __v: 0,
  },
  {
    _id: "6702bda0c57feb7bce022f71",
    objCode: "NM_6",
    question:
      'Evaluate the following statement: "All even numbers are prime numbers."',
    optionA: "This statement is true because all prime numbers are even.",
    optionB:
      "This statement is false because all even numbers are divisible by 2, and prime numbers are not divisible by any number other than 1 and themselves.",
    optionC:
      "This statement is true because all prime numbers are greater than 2.",
    optionD: "This statement is true because prime numbers can be even or odd.",
    answer: "B",
    difficultyLevel: "3",
    subject: "Mathematics",
    bloomLevel: "Evaluating",
    explanation:
      "The statement is false because even numbers are not prime numbers. Prime numbers are only those that have only two distinct positive divisors: 1 and the number itself.",
    validationResult: "Question 4: [Incorrect]",
    isCorrect: false,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:41:04.258Z",
    updatedAt: "2024-10-06T16:41:04.258Z",
    __v: 0,
  },
  {
    _id: "6702bda0c57feb7bce022f74",
    objCode: "NM_6",
    question:
      "Judge the sufficiency of the following proof that 7 is a prime number: If 7 is divisible by any number other than 1 or 7, then its remainder when divided by 7 would be 0. Since 7 is not divisible by any number other than 1 and 7, it is a prime number.",
    optionA: "This proof is sufficient and valid.",
    optionB:
      "This proof is insufficient because it does not show that 7 is greater than 2.",
    optionC:
      "This proof is sufficient but not valid because it does not follow the standard format for a proof.",
    optionD:
      "This proof is not sufficient because it does not show that 7 is only divisible by 1 and 7.",
    answer: "A",
    difficultyLevel: "3",
    subject: "Mathematics",
    bloomLevel: "Evaluating",
    explanation:
      "The proof is sufficient and valid because it shows that 7 is not divisible by any number other than 1 and itself, which is the definition of a prime number.",
    validationResult:
      'The correct statement should be: "All even numbers are not prime numbers."',
    isCorrect: false,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:41:04.657Z",
    updatedAt: "2024-10-06T16:41:04.657Z",
    __v: 0,
  },
  {
    _id: "6702bda1c57feb7bce022f77",
    objCode: "NM_6",
    question:
      'Critique the following statement: "Prime numbers are infinite in number."',
    optionA:
      "This statement is always true because there will always be more prime numbers to discover.",
    optionB: "This statement is true for all cultures and contexts.",
    optionC:
      "This statement is false because it is based on an assumption that there are an infinite number of integers.",
    optionD:
      "This statement is true because prime numbers are found in all mathematical structures.",
    answer: "C",
    difficultyLevel: "3",
    subject: "Mathematics",
    bloomLevel: "Evaluating",
    explanation:
      "The statement is false because it is based on an assumption that there are an infinite number of integers, and it has not been proven that there are an infinite number of prime numbers. While it is currently believed that there are an infinite number of prime numbers, this is not a proven fact.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:41:05.143Z",
    updatedAt: "2024-10-06T16:41:05.143Z",
    __v: 0,
  },
  {
    _id: "6702bda1c57feb7bce022f7a",
    objCode: "NM_6",
    question:
      'Evaluate the following argument: "All even numbers are composite numbers because they can be factored into two smaller numbers. Therefore, there are no prime numbers that are even."',
    optionA:
      "This argument is valid because even numbers are always composite.",
    optionB:
      "This argument is invalid because it assumes that all even numbers are composite, but this is not always the case.",
    optionC: "This argument is valid because only prime numbers are even.",
    optionD:
      "This argument is invalid because it assumes that all prime numbers are odd.",
    answer: "B",
    difficultyLevel: "3",
    subject: "Mathematics",
    bloomLevel: "Evaluating",
    explanation:
      "The argument is invalid because it assumes that all even numbers are composite, but this is not always the case. For example, 2 is an even prime number. The argument also incorrectly assumes that all prime numbers are odd. While it is true that most prime numbers are odd, there are even prime numbers as well.",
    validationResult:
      "The argument assumes that all even numbers are composite, which is not always true. It also incorrectly assumes that all prime numbers are odd.",
    isCorrect: false,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:41:05.529Z",
    updatedAt: "2024-10-06T16:41:05.529Z",
    __v: 0,
  },
  {
    _id: "6702bda2c57feb7bce022f7d",
    objCode: "NM_6",
    question: "Create a prime number greater than 100.",
    optionA: "101",
    optionB: "103",
    optionC: "102",
    optionD: "105",
    answer: "B",
    difficultyLevel: "3",
    subject: "Mathematics",
    bloomLevel: "Creating",
    explanation:
      "A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself. The only factors of 103 are 1 and 103, making it a prime number.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:41:06.260Z",
    updatedAt: "2024-10-06T16:41:06.260Z",
    __v: 0,
  },
  {
    _id: "6702bda2c57feb7bce022f80",
    objCode: "NM_6",
    question: "Generate the next prime number after 13.",
    optionA: "15",
    optionB: "17",
    optionC: "14",
    optionD: "16",
    answer: "B",
    difficultyLevel: "3",
    subject: "Mathematics",
    bloomLevel: "Creating",
    explanation:
      "To find the next prime number after 13, we start checking the numbers after 13 for their prime factorization. 17 is a prime number because its only factors are 1 and 17.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:41:06.730Z",
    updatedAt: "2024-10-06T16:41:06.730Z",
    __v: 0,
  },
  {
    _id: "6702bda3c57feb7bce022f83",
    objCode: "NM_6",
    question: "Design a step-by-step process to check if a number is prime.",
    optionA:
      "Divide the number by 2 and check if there is a remainder. If there is, the number is not prime. If not, divide by 3. Continue dividing by the next odd number until you find a factor.",
    optionB:
      "Divide the number by all numbers up to its square root. If none of them divide evenly, the number is prime.",
    optionC:
      "Multiply all the factors of 2 (if any) to get a new number, then divide the original number by this new number. Repeat this process with the new number until you reach 1. If at any point, the new number is equal to 1, the original number is not prime.",
    optionD:
      "All of the above methods are valid and can be used to check if a number is prime.",
    answer: "D",
    difficultyLevel: "3",
    subject: "Mathematics",
    bloomLevel: "Creating",
    explanation:
      "While method A and C are valid methods for checking if a number is prime, method B is a more efficient approach. By checking divisibility up to the square root of the number, we can significantly reduce the number of checks required.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T16:41:07.129Z",
    updatedAt: "2024-10-06T16:41:07.129Z",
    __v: 0,
  },
  {
    _id: "6702cdfbc57feb7bce0262a7",
    objCode: "NM_6",
    question: "1:**\nRecall the smallest prime number.",
    optionA: "0",
    optionB: "1",
    optionC: "2",
    optionD: "3",
    answer: "C",
    difficultyLevel: "1",
    subject: "Mathematics",
    bloomLevel: "Remembering",
    explanation:
      "The smallest prime number is 2, as it is the first natural number greater than 1 that is not a product of two smaller natural numbers.",
    validationResult: "**Assessment:**",
    isCorrect: false,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T17:50:51.525Z",
    updatedAt: "2024-10-06T17:50:51.525Z",
    __v: 0,
  },
  {
    _id: "6702cdfbc57feb7bce0262aa",
    objCode: "NM_6",
    question: "3:**\nIdentify the next prime number after 11.",
    optionA: "13",
    optionB: "14",
    optionC: "15",
    optionD: "16",
    answer: "A",
    difficultyLevel: "1",
    subject: "Mathematics",
    bloomLevel: "Remembering",
    explanation:
      "The next prime number after 11 is 13, as 12 is divisible by 2, 14 is divisible by 2 and 7, and 15 is divisible by 3 and 5.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T17:50:51.893Z",
    updatedAt: "2024-10-06T17:50:51.893Z",
    __v: 0,
  },
  {
    _id: "6702cdfcc57feb7bce0262ad",
    objCode: "NM_6",
    question: "1:**\nExplain why 17 is a prime number.",
    optionA: "Because it is an even number",
    optionB: "Because it has only two factors",
    optionC: "Because it is a composite number",
    optionD: "Because it is a perfect square",
    answer: "B",
    difficultyLevel: "1",
    subject: "Mathematics",
    bloomLevel: "Understanding",
    explanation:
      "A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself. 17 has only two factors: 1 and 17, hence it is a prime number.",
    validationResult: "**Assessment:**",
    isCorrect: false,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T17:50:52.431Z",
    updatedAt: "2024-10-06T17:50:52.431Z",
    __v: 0,
  },
  {
    _id: "6702cdfcc57feb7bce0262b0",
    objCode: "NM_6",
    question: '3:**\nInterpret the statement "2 is not a prime number."',
    optionA: "2 has only one factor",
    optionB: "2 has an infinite number of factors",
    optionC: "2 has exactly two factors",
    optionD: "2 is the first prime number",
    answer: "A",
    difficultyLevel: "1",
    subject: "Mathematics",
    bloomLevel: "Understanding",
    explanation:
      "A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself. Since 2 has only one factor (1), it is not a prime number.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T17:50:52.943Z",
    updatedAt: "2024-10-06T17:50:52.943Z",
    __v: 0,
  },
  {
    _id: "6702cdfdc57feb7bce0262b3",
    objCode: "NM_6",
    question:
      "1:**\nWhich of the following is the largest prime number less than 100?",
    optionA: "97",
    optionB: "89",
    optionC: "79",
    optionD: "61",
    answer: "A",
    difficultyLevel: "2",
    subject: "Mathematics",
    bloomLevel: "Applying",
    explanation:
      "The prime numbers less than 100 are 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97. Among these, 97 is the largest.",
    validationResult: "**Assessment:**",
    isCorrect: false,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T17:50:53.353Z",
    updatedAt: "2024-10-06T17:50:53.353Z",
    __v: 0,
  },
  {
    _id: "6702cdfdc57feb7bce0262b6",
    objCode: "NM_6",
    question:
      "3:**\nIllustrate the difference between prime and composite numbers using the first 10 natural numbers.",
    optionA: "1, 2, 3, 4, 5, 6, 7, 8, 9, 10",
    optionB: "1, 2, 3, 5, 7, 9, 11, 13, 17, 19",
    optionC: "1, 4, 6, 8, 9, 10, 12, 14, 15, 16",
    optionD: "2, 3, 5, 7, 11, 13, 17, 19, 23, 29",
    answer: "D",
    difficultyLevel: "2",
    subject: "Mathematics",
    bloomLevel: "Applying",
    explanation:
      "Prime numbers are numbers greater than 1 that have no divisors other than 1 and themselves. Composite numbers are numbers that have more than two factors. In the first 10 natural numbers, the prime numbers are 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, and the composite numbers are 4, 6, 8, 9, 10, 12, 14, 15, 16.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T17:50:53.902Z",
    updatedAt: "2024-10-06T17:50:53.902Z",
    __v: 0,
  },
  {
    _id: "6702cdfec57feb7bce0262b9",
    objCode: "NM_6",
    question:
      "1:**\nAnalyze the given set of numbers and determine which one is a prime number.\n{2, 4, 7, 10, 13}",
    optionA: "2",
    optionB: "4",
    optionC: "10",
    optionD: "13",
    answer: "A",
    difficultyLevel: "2",
    subject: "Mathematics",
    bloomLevel: "Analyzing",
    explanation:
      "A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself. Among the given numbers, only 2 and 13 are prime numbers.",
    validationResult: "**Assessment:**",
    isCorrect: false,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T17:50:54.302Z",
    updatedAt: "2024-10-06T17:50:54.302Z",
    __v: 0,
  },
  {
    _id: "6702cdfec57feb7bce0262bc",
    objCode: "NM_6",
    question:
      "3:**\nDistinguish between a prime number and a composite number using the following statements:\nI. A prime number has exactly two distinct positive divisors.\nII. A composite number has more than two distinct positive divisors.\nIII. A prime number is always an even number.",
    optionA: "I and II are true, III is false.",
    optionB: "I and III are true, II is false.",
    optionC: "I and II are false, III is true.",
    optionD: "All statements are false.",
    answer: "A",
    difficultyLevel: "2",
    subject: "Mathematics",
    bloomLevel: "Analyzing",
    explanation:
      "Statement I is true as a prime number has exactly two distinct positive divisors: 1 and itself. Statement II is true as a composite number has more than two distinct positive divisors. Statement III is false as a prime number is not always an even number; only 2 is an even prime number.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T17:50:54.883Z",
    updatedAt: "2024-10-06T17:50:54.883Z",
    __v: 0,
  },
  {
    _id: "6702cdffc57feb7bce0262bf",
    objCode: "NM_6",
    question:
      '1:**\nEvaluate the statement: "The product of two prime numbers is always a prime number."',
    optionA: "True",
    optionB: "False",
    optionC: "True, only if the two prime numbers are consecutive",
    optionD: "True, only if the two prime numbers are odd",
    answer: "B",
    difficultyLevel: "3",
    subject: "Mathematics",
    bloomLevel: "Evaluating",
    explanation:
      "The product of two prime numbers is always a composite number (e.g., 2 and 3 produce 6, which is not a prime number).",
    validationResult: "**Assessment:**",
    isCorrect: false,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T17:50:55.352Z",
    updatedAt: "2024-10-06T17:50:55.352Z",
    __v: 0,
  },
  {
    _id: "6702cdffc57feb7bce0262c2",
    objCode: "NM_6",
    question:
      '3:**\nJudge the following claim: "There are infinitely many prime numbers less than 100."',
    optionA: "True",
    optionB: "False",
    optionC: "True, but only if 100 is replaced with a larger number",
    optionD: "True, but only if 100 is replaced with a smaller number",
    answer: "A",
    difficultyLevel: "3",
    subject: "Mathematics",
    bloomLevel: "Evaluating",
    explanation:
      "There are 25 prime numbers less than 100 (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97), demonstrating that there are infinitely many prime numbers in this range.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T17:50:55.832Z",
    updatedAt: "2024-10-06T17:50:55.832Z",
    __v: 0,
  },
  {
    _id: "6702ce00c57feb7bce0262c5",
    objCode: "NM_6",
    question:
      "1:**\nCreate a new prime number between 50 and 100 using the Sieve of Eratosthenes method.",
    optionA: "61",
    optionB: "67",
    optionC: "71",
    optionD: "79",
    answer: "B",
    difficultyLevel: "3",
    subject: "Mathematics",
    bloomLevel: "Creating",
    explanation:
      "The Sieve of Eratosthenes method involves crossing out multiples of each prime number starting from 2. Between 50 and 100, the primes are 53, 59, 61, 67, 71, 73, 79, 83, 89, and 97. The first number in this list that is not a multiple of any of the previous primes is 67.",
    validationResult: "**Assessment:**",
    isCorrect: false,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T17:50:56.297Z",
    updatedAt: "2024-10-06T17:50:56.297Z",
    __v: 0,
  },
  {
    _id: "6702ce01c57feb7bce0262c8",
    objCode: "NM_6",
    question:
      "3:**\nGenerate a list of the first 10 prime numbers using the trial division method.",
    optionA: "2, 3, 5, 7, 11, 13, 17, 19, 23, 29",
    optionB: "2, 4, 6, 8, 10, 12, 14, 16, 18, 20",
    optionC: "2, 3, 5, 7, 9, 11, 13, 15, 17, 19",
    optionD: "2, 3, 5, 7, 11, 13, 17, 19, 23, 29",
    answer: "D",
    difficultyLevel: "3",
    subject: "Mathematics",
    bloomLevel: "Creating",
    explanation:
      "The trial division method involves checking each number for divisibility by all prime numbers less than its square root. The first 10 prime numbers are 2, 3, 5, 7, 11, 13, 17, 19, 23, and 29.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T17:50:57.263Z",
    updatedAt: "2024-10-06T17:50:57.263Z",
    __v: 0,
  },
  {
    _id: "6702de1fc57feb7bce027f53",
    objCode: "NM_6",
    question: "2:**\nIdentify the smallest prime number.",
    optionA: "0",
    optionB: "1",
    optionC: "2",
    optionD: "3",
    answer: "C",
    difficultyLevel: "1",
    subject: "Mathematics",
    bloomLevel: "Remembering",
    explanation:
      "The smallest prime number is 2, as it is the first natural number greater than 1 that is not divisible by any other number.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T18:59:43.234Z",
    updatedAt: "2024-10-06T18:59:43.234Z",
    __v: 0,
  },
  {
    _id: "6702de20c57feb7bce027f56",
    objCode: "NM_6",
    question: "3:**\nRecall the total number of prime numbers less than 20.",
    optionA: "5",
    optionB: "8",
    optionC: "10",
    optionD: "12",
    answer: "B",
    difficultyLevel: "1",
    subject: "Mathematics",
    bloomLevel: "Remembering",
    explanation:
      "The prime numbers less than 20 are 2, 3, 5, 7, 11, 13, 17, and 19, making a total of 8 prime numbers.",
    validationResult: "**Assessment:**",
    isCorrect: false,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T18:59:44.312Z",
    updatedAt: "2024-10-06T18:59:44.312Z",
    __v: 0,
  },
  {
    _id: "6702de21c57feb7bce027f59",
    objCode: "NM_6",
    question:
      "2:**\nSummarize the relationship between 13 and its prime factors.",
    optionA: "13 is a prime factor of itself.",
    optionB: "13 is a composite number with prime factors 3 and 7.",
    optionC: "13 is a prime number with prime factors 1 and 13.",
    optionD: "13 is a prime number with no prime factors.",
    answer: "D",
    difficultyLevel: "1",
    subject: "Mathematics",
    bloomLevel: "Understanding",
    explanation:
      "A prime number has no other divisors other than 1 and itself. Therefore, 13 is a prime number with no prime factors other than 1 and 13.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T18:59:45.319Z",
    updatedAt: "2024-10-06T18:59:45.319Z",
    __v: 0,
  },
  {
    _id: "6702de22c57feb7bce027f5c",
    objCode: "NM_6",
    question:
      '3:**\nInterpret the statement "2 is not a prime number" in the context of prime numbers.',
    optionA: "2 is the only even prime number.",
    optionB: "2 has only one positive divisor.",
    optionC: "2 has an infinite number of divisors.",
    optionD: "2 has exactly two positive divisors.",
    answer: "B",
    difficultyLevel: "1",
    subject: "Mathematics",
    bloomLevel: "Understanding",
    explanation:
      "A prime number has exactly two distinct positive divisors: 1 and itself. Since 2 has only one positive divisor (1), it is not a prime number.",
    validationResult: "**Assessment:**",
    isCorrect: false,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T18:59:46.248Z",
    updatedAt: "2024-10-06T18:59:46.248Z",
    __v: 0,
  },
  {
    _id: "6702de24c57feb7bce027f5f",
    objCode: "NM_6",
    question:
      "2:**\nDemonstrate the difference between a prime number and a composite number using the first 20 natural numbers.\nWhich of the following is a composite number?",
    optionA: "7",
    optionB: "10",
    optionC: "15",
    optionD: "18",
    answer: "D",
    difficultyLevel: "2",
    subject: "Mathematics",
    bloomLevel: "Applying",
    explanation:
      "A prime number has only two distinct positive divisors: 1 and itself. A composite number has more than two divisors. Among the options, 18 is a composite number (divisible by 1, 2, 3, 6, 9, and 18).",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T18:59:48.674Z",
    updatedAt: "2024-10-06T18:59:48.674Z",
    __v: 0,
  },
  {
    _id: "6702de25c57feb7bce027f62",
    objCode: "NM_6",
    question:
      "3:**\nIllustrate the concept of a twin prime using the first 30 prime numbers.\nWhat are the twin primes between 20 and 30?",
    optionA: "23 and 29",
    optionB: "29 and 31",
    optionC: "31 and 37",
    optionD: "37 and 41",
    answer: "A",
    difficultyLevel: "2",
    subject: "Mathematics",
    bloomLevel: "Applying",
    explanation:
      "Twin primes are pairs of primes that differ by two. The twin primes between 20 and 30 are 23 and 29.",
    validationResult: "**Assessment:**",
    isCorrect: false,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T18:59:49.615Z",
    updatedAt: "2024-10-06T18:59:49.615Z",
    __v: 0,
  },
  {
    _id: "6702de26c57feb7bce027f65",
    objCode: "NM_6",
    question:
      "2:**\nCompare the number of prime numbers less than 50 and the number of prime numbers less than 100. Which of the following statements is true?",
    optionA:
      "There are more prime numbers less than 50 than there are less than 100.",
    optionB:
      "There are fewer prime numbers less than 50 than there are less than 100.",
    optionC:
      "There are the same number of prime numbers less than 50 as there are less than 100.",
    optionD:
      "There is no way to compare the two without additional information.",
    answer: "B",
    difficultyLevel: "2",
    subject: "Mathematics",
    bloomLevel: "Analyzing",
    explanation:
      "There are 15 prime numbers less than 50 (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47) and 25 prime numbers less than 100 (adding 2 more: 53 and 59). Therefore, there are fewer prime numbers less than 50 than there are less than 100.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T18:59:50.776Z",
    updatedAt: "2024-10-06T18:59:50.776Z",
    __v: 0,
  },
  {
    _id: "6702de28c57feb7bce027f68",
    objCode: "NM_6",
    question:
      "3:**\nDistinguish between the following pairs of numbers in terms of their primality:\n- 17 and 25\n- 31 and 36\n- 41 and 44",
    optionA:
      "17 is prime, 25 is composite; 31 is prime, 36 is composite; 41 is prime, 44 is composite.",
    optionB:
      "17 is composite, 25 is prime; 31 is composite, 36 is prime; 41 is composite, 44 is prime.",
    optionC:
      "17 is prime, 25 is prime; 31 is prime, 36 is prime; 41 is prime, 44 is prime.",
    optionD:
      "17 is composite, 25 is composite; 31 is composite, 36 is composite; 41 is composite, 44 is composite.",
    answer: "A",
    difficultyLevel: "2",
    subject: "Mathematics",
    bloomLevel: "Analyzing",
    explanation:
      "17 is a prime number, while 25 is a composite number (25 = 5 x 5). Similarly, 31 is a prime number, and 36 is a composite number (36 = 2 x 18 = 2 x 2 x 9). Lastly, 41 is a prime number, and 44 is a composite number (44 = 2 x 22 = 2 x 2 x 11).",
    validationResult: "**Assessment:**",
    isCorrect: false,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T18:59:52.835Z",
    updatedAt: "2024-10-06T18:59:52.835Z",
    __v: 0,
  },
  {
    _id: "6702de29c57feb7bce027f6b",
    objCode: "NM_6",
    question:
      '2:**\nCritique the following method for finding prime numbers: "Divide each number by all the numbers less than it until a factor is found."',
    optionA: "This method is efficient and can find all prime numbers.",
    optionB: "This method is inefficient but can find all prime numbers.",
    optionC: "This method cannot find all prime numbers.",
    optionD:
      "This method is efficient and can find all prime numbers up to a certain limit.",
    answer: "B",
    difficultyLevel: "3",
    subject: "Mathematics",
    bloomLevel: "Evaluating",
    explanation:
      "While this method can find all prime numbers, it's inefficient because it checks divisibility with every number less than the given number, leading to many unnecessary calculations.",
    validationResult: "The question is correct.",
    isCorrect: true,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T18:59:53.296Z",
    updatedAt: "2024-10-06T18:59:53.296Z",
    __v: 0,
  },
  {
    _id: "6702de29c57feb7bce027f6e",
    objCode: "NM_6",
    question:
      '3:**\nJudge the following claim: "The product of two prime numbers is always a prime number."',
    optionA:
      "True, as the product of two prime numbers is always a prime number.",
    optionB:
      "True, as the product of two prime numbers is always a composite number.",
    optionC:
      "False, as the product of two prime numbers can be a prime number or a composite number.",
    optionD: "False, as the product of two prime numbers is always 1.",
    answer: "C",
    difficultyLevel: "3",
    subject: "Mathematics",
    bloomLevel: "Evaluating",
    explanation:
      "The product of two prime numbers is always a composite number (except for the case where both primes are 2, in which case the product is 4, which is also composite). Therefore, the statement is false.",
    validationResult: "**Assessment:**",
    isCorrect: false,
    learningObjective: "prime numbers",
    recommendation: [],
    createdAt: "2024-10-06T18:59:53.715Z",
    updatedAt: "2024-10-06T18:59:53.715Z",
    __v: 0,
  },
];
