import { useSelector } from "react-redux";

const ParentReport = () => {
  const userInfo = useSelector((state) => state.user.userInfo);
  console.log({ userInfo });

  return (
    <div className="mx-3 md:mx-24 my-9">
      <h1 className="text-3xl font-medium text-center mb-12">
        Marvelous Osato's Assesment Feedback
      </h1>

      <p className="capitalize text-lg">Dear {userInfo?.fullName},</p>
      <p className="mt-4">
        We are pleased to present the latest report on your daughter, Marvelous
        Osato's, academic progress. This report provides a comprehensive view of
        her performance across all her subjects: Mathematics, Science, English,
        and History. We will draw links between different subjects, highlighting
        her interdisciplinary strengths and areas for improvement, and relate
        her performance to her aspiration of becoming a Software Engineer.
      </p>
      <p className="mt-4">
        Overall, Marvelous has demonstrated excellent performance across all
        subjects, with an average score of 85.6%. Her strength lies in her
        understanding of abstract concepts and her ability to apply theoretical
        knowledge to practical problems. This is evident in her outstanding
        performance in Mathematics, Science, and English, where she consistently
        ranks in the 80th-95th percentile.
      </p>
      <p className="mt-4">
        In <span className="font-medium">Mathematics</span>, Marvelous's strong
        suit is her ability to express fractions, decimals, and percentages, as
        well as her understanding of bearing and distance. She excelled in these
        areas with scores of 80th and 50th percentile, respectively. However,
        she needs to improve her understanding of fractions, particularly their
        meaning and types, which is currently her underperforming objective. We
        recommend that she focuses on this area by practicing basic fraction
        problems, reading books on fractions, and working with online resources.
      </p>
      <p className="mt-4">
        In <span className="font-medium">Science</span>, Marvelous's
        top-performing objectives are Scientific Inquiry and Lab Report Writing,
        where she scored 95th and 90th percentile, respectively. Her ability to
        conduct experiments and present her findings effectively sets her apart.
        However, she needs to improve her Physics Calculations, which currently
        ranks in the 70th percentile. We suggest she spends extra time on this
        topic, focusing on understanding the underlying principles and
        practicing problems with step-by-step solutions.
      </p>
      <p className="mt-4">
        In <span className="font-medium">English</span>, Marvelous's strengths
        lie in Literary Analysis and Creative Writing, where she scored 89th and
        87th percentile, respectively. She has a keen eye for detail and a
        creative mind. However, she needs to improve her Essay Structure, which
        is currently her underperforming objective. We recommend she focuses on
        understanding the structure of an essay, including the introduction,
        body, and conclusion, and practices writing essays with these
        structures.
      </p>
      <p className="mt-4">
        In <span className="font-medium">History</span>, Marvelous's strength is
        her ability to analyze sources and participate in historical debates,
        where she scored 80th and 79th percentile, respectively. However, she
        needs to improve her Chronological Understanding, which currently ranks
        in the 68th percentile. We suggest she focuses on understanding
        historical timelines and the sequencing of events.
      </p>
      <p className="mt-4">
        Marvelous has excellent behavior in all her subjects, and her attendance
        is commendable. However, we encourage her to maintain this high level of
        dedication and discipline, especially in History where her attitude
        towards learning is only satisfactory.
      </p>
      <p className="mt-4">
        In conclusion, Marvelous's current performance is impressive, and with a
        little more focus and dedication, she can excel in all her subjects. As
        she aspires to become a Software Engineer, her mathematical and
        scientific skills are particularly important. We encourage her to
        continue her current trajectory and seize every opportunity to improve
        her weaker areas.
      </p>
      <p className="mt-4">
        We hope this report provides you with valuable insights into Marvelous's
        academic progress and helps guide her future learning.
      </p>
      <i className="mt-4 block">
        This report was generated by Eddey (EDATECH Limited AI-based educational
        assistant) on behalf of Ms. Emily Okon based on the student's
        performance.
      </i>
    </div>
  );
};

export default ParentReport;
