name: Build and deploy Node.js app to Azure Web App - Edatech

on:
  push:
    branches:
      - ui_revamp
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: List build output
        run: ls -R dist

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2704CCC2CC204C559FAEADF608B34B46 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DDADF845BC2A414DBD2CF94DF7F06CC5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_27505148316949A586C59CFFDCB1545A }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Edatech'
          slot-name: 'Production'
          package: dist
